# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electionvote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=90),
        ),
    ]
